### ISSUE TITLE
cannot find module 'zappa'

### ISSUE THREAD

**Issue by ghost** [mauricemach/zappa#34] opened 2011-04-13 19:21 UTC
I used NPM to install zappa.  install happened without issue.  created the cuppa.coffee and then ran zappa cuppa.coffee and I get this: 

Error: Cannot find module 'zappa'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.4/package/bin/zappa.coffee:9:11)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.4/package/bin/zappa.coffee:139:4)
    at Module._compile (module.js:404:26)
    at Object.run (/usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/coffee-script.js:55:19)
    at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:115:29
    at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:85:26
    at [object Object].<anonymous> (fs.js:107:5)

Here comes some versions for ya:
NPM: 0.3.18
Node:  0.4.5
zappa: Error: Cannot find module 'zappa'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.4/package/bin/zappa.coffee:9:11)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.4/package/bin/zappa.coffee:139:4)
    at Module._compile (module.js:404:26)
    at Object.run (/usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/coffee-script.js:55:19)
    at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:115:29
    at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:85:26
    at [object Object].<anonymous> (fs.js:107:5)

I get that error with everything I do using zappa.

**Comment by ghost** [comment] 2011-04-13 19:21
Oh, I'm on mac 10.6.7 using zsh if that matters?

**Comment by kozmikyak** [comment] 2011-04-14 14:35
Because of API changes in Connect, Express, and NPM, there are a bunch of mods needed to get it working.  I don't have the required expertise yet to submit through Git, but two of my posts in another thread could get you a working Zappa install.

https://github.com/mauricemach/zappa/issues/27#issuecomment-991983

**Comment by ghost** [comment] 2011-04-14 14:43
thanks for the help. I learned that it had to do with not having the NODE_PATH environment variable set. so, doing that fixed the problem. sorry I forgot to comment and close.

Brec Carson

**Comment by kozmikyak** [comment] 2011-04-14 15:26
On 4/14/2011 9:43 AM, brecatrally wrote:

> thanks for the help. I learned that it had to do with not having the NODE_PATH environment variable set. so, doing that fixed the problem. sorry I forgot to comment and close.
> Interesting.  For some people setting NODE_PATH fixes the problem.  On 
> my end it didn't fix it and those changes seem needed.

I'm liking CoffeeScript and Node.JS so far.

**Comment by tobsn** [comment] 2011-04-19 22:18
did not fix it for me. still broken. fresh npm install from just 20 minutes ago.

**Comment by TrevorBurnham** [comment] 2011-04-28 23:54
Dupe of #27, I think... I'm able to install by cloning the repo and then running

```
npm install
```

from that directory (with `-g` if you're using npm 1.0 RC).

**Comment by alduro** [comment] 2011-05-05 14:29
same problem here. npm install -g zappa - Error: Cannot find module 'zappa'
but other modules installde global are required with no problem - express, backbone, stylus, for instance.
I'm having problems with zappa and coffeekup

**Comment by cmelendez** [comment] 2011-06-12 03:43
it's npm 'problem', not zappa.

quick fix:

npm install zappa -g
npm link zappa

**Closed as completed** 2011-07-14 06:46 UTC
