### ISSUE TITLE
Add connect middleware / expose Express app

### ISSUE THREAD

**Issue by ggoodman** [mauricemach/zappa#26] opened 2011-01-07 17:38 UTC
In looking at the possibility of adding middleware to zappa apps, I noted that there doesn't seem be be a way to get access to the Express app itself.  This means that plugging in 3rd party middleware is not an obvious process and seems to require tweaking zappa itself.

**Comment by mauricemach** [comment] 2011-01-14 05:29
Duplicate of [#25](https://github.com/mauricemach/zappa/issues#issue/25).

**Comment by mauricemach** [comment] 2011-08-03 14:14
Implemented in 0.2.0beta, please see #25.

**Closed as completed by mauricemach** 2011-08-03 14:14 UTC
Labels: enhancement, duplicate
